# Generated by Django 5.0.4 on 2024-05-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=3)),
                ('isBookmarked', models.BooleanField(default=False)),
                ('isTrending', models.BooleanField(default=False)),
                ('thumbnail_trending_small', models.CharField(blank=True, max_length=300)),
                ('thumbnail_trending_large', models.CharField(blank=True, max_length=300)),
                ('thumbnail_regular_small', models.CharField(max_length=300)),
                ('thumbnail_regular_medium', models.CharField(max_length=300)),
                ('thumbnail_regular_large', models.CharField(max_length=300)),
            ],
        ),
    ]
