# Generated by Django 5.0.4 on 2024-05-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumbnail_regular_large',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumbnail_regular_medium',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumbnail_regular_small',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumbnail_trending_large',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumbnail_trending_small',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
